meanREST <- mean(misure$V2)
meanMQTT_0 <- mean(misure$V1)
meanMQTT_1 <- mean(misure$V4) 
devstREST <- sd(misure$V2)
devstMQTT_0 <- sd(misure$V1)
devstMQTT_1 <- sd(misure$V4)
means <- c(meanMQTTQ_0, meanMQTT_1,meanREST)
means <- c(meanMQTT_0, meanMQTT_1,meanREST)
ciwMQTTQ_0 <- (1.960) * (devstMQTT_0/sqrt(30))
ciwMQTTQ_1 <- (1.960) * (devstMQTT_1/sqrt(30))
ciwREST <- (1.960) * (devstREST/sqrt(30))
ciws <- c(ciwMQTTQ_0,ciwMQTTQ_1,ciwREST)
install.packages("gplots")
library(gplots)
plotCI(x = means, uiw=ciws, gap =0.2, col = "black", barcol = "blue",main="Visual Test with 95% confidence level")
