meanMQTTQOS0 <- mean(MisureTempi$V1)
meanREST <- mean(MisureTempi$V2)
meanWEBHOOK <- mean(MisureTempi$V3)
devstWEBHOOK <- sd(MisureTempi$V3)
devstREST <- sd(MisureTempi$V2)
devstMQTTQOS0 <- sd(MisureTempi$V1)
means <- c(meanMQTTQOS0,meanREST,meanWEBHOOK)
ciwMQTTQOS0 <- (1.645) * (devstMQTTQOS0/sqrt(30))
ciwREST <- (1.645) * (devstREST/sqrt(30))
ciwWEBHOOK <- (1.645) * (devstWEBHOOK/sqrt(30))
ciws <- c(ciwMQTTQOS0,ciwREST,ciwWEBHOOK)
plotCI(x = means, uiw=ciws, gap =0.2,
       col = "black", barcol = "blue",main="Visual Test with 90% confidence level")